version: "3.7"

services:
  envoy:
    build:
      context: envoy
      dockerfile: Dockerfile
    container_name: envoy
    ports:
      - 8080:8080

  broker:
    build:
      context: backend
      dockerfile: build/Dockerfile
    container_name: broker
    ports:
      - 1883:1883

  server:
    build:
      context: server
      dockerfile: build/Dockerfile
    container_name: info
    depends_on:
      - info_db
    ports:
      - 8081:8080

  info_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: info
    container_name: "db-info"
    volumes:
      - "./tmp/db/info:/var/lib/mysql"
    ports:
      - 33306:3306
