version: "3.7"

services:
  auth:
    build:
      context: auth
      dockerfile: build/Dockerfile
    container_name: auth1
    volumes:
      - ./backend/auth:/app
    depends_on:
      - auth_db
      - redis

  auth_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: auth
    container_name: "db-auth1"
    volumes:
      - "./tmp/db/auth:/var/lib/mysql"

  redis:
    image: redis:latest
    container_name: redis1
    ports:
      - "63791:6379"
    restart: always

  envoy:
    build:
      context: envoy
      dockerfile: Dockerfile
    container_name: envoy
    ports:
      - 8080:8080

  broker:
    build:
      context: backend
      dockerfile: build/Dockerfile
    container_name: broker
    ports:
      - 1883:1883

  server:
    build:
      context: server
      dockerfile: build/Dockerfile
    container_name: info
    depends_on:
      - info_db
    ports:
      - 8081:8080

  info_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: info
    container_name: "db-info"
    volumes:
      - "./tmp/db/info:/var/lib/mysql"
    ports:
      - 33306:3306
