version: '3.7'

services:
  server:
    build:
      context: server
      dockerfile: build/Dockerfile
    container_name: info
    depends_on:
      - info_db
    ports:
      - 8080:8080

  info_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: info
    container_name: 'db-info'
    volumes:
      - "./tmp/db/auth:/var/lib/mysql"
    ports:
      - 33306:3306