// Code generated by entc, DO NOT EDIT.

package data

import (
	"time"
)

const (
	// Label holds the string label denoting the data type in the database.
	Label = "data"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// FieldRecordedAt holds the string denoting the recorded_at field in the database.
	FieldRecordedAt = "recorded_at"
	// EdgeFeed holds the string denoting the feed edge name in mutations.
	EdgeFeed = "feed"
	// Table holds the table name of the data in the database.
	Table = "data"
	// FeedTable is the table that holds the feed relation/edge.
	FeedTable = "data"
	// FeedInverseTable is the table name for the Feed entity.
	// It exists in this package in order to avoid circular dependency with the "feed" package.
	FeedInverseTable = "feeds"
	// FeedColumn is the table column denoting the feed relation/edge.
	FeedColumn = "feed_data"
)

// Columns holds all SQL columns for data fields.
var Columns = []string{
	FieldID,
	FieldData,
	FieldRecordedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "data"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"feed_data",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRecordedAt holds the default value on creation for the "recorded_at" field.
	DefaultRecordedAt time.Time
)
