// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/manhrev/IOT/server/pkg/ent/data"
	"github.com/manhrev/IOT/server/pkg/ent/feed"
	"github.com/manhrev/IOT/server/pkg/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dataFields := schema.Data{}.Fields()
	_ = dataFields
	// dataDescRecordedAt is the schema descriptor for recorded_at field.
	dataDescRecordedAt := dataFields[1].Descriptor()
	// data.DefaultRecordedAt holds the default value on creation for the recorded_at field.
	data.DefaultRecordedAt = dataDescRecordedAt.Default.(time.Time)
	feedFields := schema.Feed{}.Fields()
	_ = feedFields
	// feedDescCreatedAt is the schema descriptor for created_at field.
	feedDescCreatedAt := feedFields[1].Descriptor()
	// feed.DefaultCreatedAt holds the default value on creation for the created_at field.
	feed.DefaultCreatedAt = feedDescCreatedAt.Default.(time.Time)
}
