// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Data is the predicate function for data builders.
type Data func(*sql.Selector)

// Feed is the predicate function for feed builders.
type Feed func(*sql.Selector)
