// Code generated by ent, DO NOT EDIT.

package feed

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/manhrev/IOT/server/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// FeedName applies equality check predicate on the "feed_name" field. It's identical to FeedNameEQ.
func FeedName(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFeedName), v))
	})
}

// FeedNameEQ applies the EQ predicate on the "feed_name" field.
func FeedNameEQ(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFeedName), v))
	})
}

// FeedNameNEQ applies the NEQ predicate on the "feed_name" field.
func FeedNameNEQ(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFeedName), v))
	})
}

// FeedNameIn applies the In predicate on the "feed_name" field.
func FeedNameIn(vs ...string) predicate.Feed {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldFeedName), v...))
	})
}

// FeedNameNotIn applies the NotIn predicate on the "feed_name" field.
func FeedNameNotIn(vs ...string) predicate.Feed {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldFeedName), v...))
	})
}

// FeedNameGT applies the GT predicate on the "feed_name" field.
func FeedNameGT(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFeedName), v))
	})
}

// FeedNameGTE applies the GTE predicate on the "feed_name" field.
func FeedNameGTE(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFeedName), v))
	})
}

// FeedNameLT applies the LT predicate on the "feed_name" field.
func FeedNameLT(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFeedName), v))
	})
}

// FeedNameLTE applies the LTE predicate on the "feed_name" field.
func FeedNameLTE(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFeedName), v))
	})
}

// FeedNameContains applies the Contains predicate on the "feed_name" field.
func FeedNameContains(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFeedName), v))
	})
}

// FeedNameHasPrefix applies the HasPrefix predicate on the "feed_name" field.
func FeedNameHasPrefix(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFeedName), v))
	})
}

// FeedNameHasSuffix applies the HasSuffix predicate on the "feed_name" field.
func FeedNameHasSuffix(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFeedName), v))
	})
}

// FeedNameEqualFold applies the EqualFold predicate on the "feed_name" field.
func FeedNameEqualFold(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFeedName), v))
	})
}

// FeedNameContainsFold applies the ContainsFold predicate on the "feed_name" field.
func FeedNameContainsFold(v string) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFeedName), v))
	})
}

// HasData applies the HasEdge predicate on the "data" edge.
func HasData() predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DataTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DataTable, DataColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDataWith applies the HasEdge predicate on the "data" edge with a given conditions (other predicates).
func HasDataWith(preds ...predicate.Data) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DataInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DataTable, DataColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Feed) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Feed) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Feed) predicate.Feed {
	return predicate.Feed(func(s *sql.Selector) {
		p(s.Not())
	})
}
